ALTER TABLE CUSTOMERS
ALTER COLUMN INACTIVE SET DEFAULT FALSE;

ALTER TABLE PRODUCTS
ALTER COLUMN INACTIVE SET DEFAULT FALSE;

ALTER TABLE SUPPLIERS
ALTER COLUMN INACTIVE SET DEFAULT FALSE;

ALTER TABLE USERS
ALTER COLUMN INACTIVE SET DEFAULT FALSE;