CREATE TABLE CATEGORIES (
    CATEGORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    COLOR VARCHAR(9) NOT NULL,
    PREFIX VARCHAR(10) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    IMAGE LONGTEXT,
    CONSTRAINT UK_CATEGORY_NAME UNIQUE (NAME)
);

CREATE TABLE CUSTOMERS (
    CUST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PHONE VARCHAR(20) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT UK_CUSTOMER_PHONE UNIQUE (PHONE),
    CONSTRAINT UK_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PRODUCTS (
    PROD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    COST_PRICE DECIMAL(10,2) NOT NULL,
    REORDER_LEVEL INT NOT NULL,
    STOCK_QTY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
    SKU VARCHAR(50) NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    IMAGE LONGTEXT,
    CONSTRAINT UK_PRODUCT_SKU UNIQUE (SKU),
    CONSTRAINT UK_PRODUCT_NAME UNIQUE (NAME),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE TABLE SUPPLIERS (
    SUPP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    PHONE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(60) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT UK_SUPPLIER_NAME UNIQUE (NAME),
    CONSTRAINT UK_SUPPLIER_PHONE UNIQUE (PHONE),
    CONSTRAINT UK_SUPPLIER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_SUPPLIER_ADDRESS UNIQUE (ADDRESS)
);

CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWD_CIPHERTEXT VARCHAR(255) NOT NULL,
    ROLE ENUM('ADMIN','CASHIER') NOT NULL,
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PURCHASE_ORDER (
    PO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INACTIVE TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SUPP_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STATUS ENUM('CANCELLED','DELIVERED','PENDING') NOT NULL,
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIERS(SUPP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE PURCHASE_ORDER_ITEM (
    POI_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PO_ID BIGINT NOT NULL,
    PROD_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_COST DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (PO_ID) REFERENCES PURCHASE_ORDER(PO_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
);

CREATE TABLE SALES_ORDER (
    SO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CUST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PAYMENT_METHOD ENUM('CARD','CASH') NOT NULL,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SALES_ORDER_ITEM (
    SOI_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SO_ID BIGINT NOT NULL,
    PROD_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (SO_ID) REFERENCES SALES_ORDER(SO_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID)
);
